services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      # - NODE_ENV=development
      - NODE_ENV=production
    # command: npm start
    command: npm run dev
